require "time"

task :specs_report do |task, args|
    time = Time.now.utc.iso8601.tr(":", "")
    report = "--format html --out=logs/report_#{time}.html"
    sh "cucumber #{report}"
end

task :specs, [:tags, :browser] do |task, args|
    time = Time.now.utc.iso8601.tr(":", "")
    report = "--format html --out=logs/report_#{time}.html"
    sh "cucumber #{args[:tags]} #{report} #{args[:browser]}"
end